# Generated by Django 2.0.7 on 2019-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_auto_20191024_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='grades_obtained',
        ),
        migrations.RemoveField(
            model_name='students',
            name='max_grades',
        ),
        migrations.RemoveField(
            model_name='students',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='students',
            name='programme_studied',
        ),
        migrations.RemoveField(
            model_name='students',
            name='year_of_study',
        ),
    ]
