# Generated by Django 2.0.7 on 2019-12-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_auto_20191215_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='industry_interested',
        ),
        migrations.RemoveField(
            model_name='students',
            name='skills_interested',
        ),
        migrations.AddField(
            model_name='students',
            name='student_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='technical_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.TechnicalSubject'),
        ),
    ]
