# Generated by Django 2.0.7 on 2019-12-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_auto_20191215_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.StudentType'),
        ),
    ]
