# Generated by Django 2.0.7 on 2019-12-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_auto_20191222_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_post',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Employeeee'),
        ),
    ]
