# Generated by Django 2.0.7 on 2019-12-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0043_auto_20191224_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeee',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='graduate',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
