# Generated by Django 2.0.7 on 2019-12-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0045_studentfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfollowing',
            name='follower_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentfollowing',
            name='following_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
