# Generated by Django 2.0.7 on 2020-01-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0048_auto_20200104_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_post',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Professor'),
        ),
    ]
